import type { Persona, SourceOption } from "@/types";

/** Avatares line-art del diseño (`public/assets/design/avatars/`). */
const avatar = (file: string) => `/assets/design/avatars/${file}`;

export const PRESET_PERSONAS: Persona[] = [
  {
    id: "early-adopter",
    name: "Early Adopter Tech",
    category: "simple",
    group: "core",
    initials: "EA",
    avatarBg: "var(--color-accent-100)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("early-adopter.png"),
    description:
      "Technical user who tolerates bugs and looks for innovation. Judges whether the concept is strong even if execution is rough.",
    traits: ["Tolerates bugs", "Seeks innovation", "Gives technical feedback", "Compares alternatives"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "ui-designer",
    category: "pro",
    group: "core",
    name: "UI Designer",
    initials: "UI",
    avatarBg: "var(--color-accent-100)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("ui-designer.png"),
    description:
      "Evaluates visual hierarchy, component consistency, spacing, typography, contrast, and WCAG accessibility.",
    traits: ["Visual hierarchy", "Design system consistency", "WCAG accessibility", "Spacing and rhythm", "Contrast and legibility"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "product-strategist",
    category: "pro",
    group: "core",
    name: "Product Strategist",
    initials: "PS",
    avatarBg: "var(--color-warning-2)",
    avatarColor: "var(--color-warning-1)",
    avatarPhoto: avatar("product-strategist.png"),
    description: "Evaluates value proposition, activation, retention, and monetization.",
    traits: ["Value proposition", "Activation and aha moment", "Retention and churn", "Pricing clarity", "Impact metrics"],
    frustration: "medium",
    techLevel: "high",
  },
  {
    id: "busy-manager",
    name: "Busy Manager",
    category: "simple",
    group: "core",
    initials: "MO",
    avatarBg: "var(--color-warning-2)",
    avatarColor: "var(--color-warning-1)",
    avatarPhoto: avatar("busy-manager.png"),
    description: "Short on time; needs to understand the value in 10 seconds. If it is not clear, they leave.",
    traits: ["Impatient", "Results-oriented", "Delegates tasks", "Looks for clear ROI"],
    frustration: "high",
    techLevel: "medium",
  },
  {
    id: "skeptic",
    name: "Pragmatic Skeptic",
    category: "simple",
    group: "core",
    initials: "EP",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("skeptic-v2.png"),
    description: "Has seen many tools fail. Needs concrete proof and real use cases.",
    traits: ["Skeptical", "Asks for evidence", "Compares prices", "Looks for success stories"],
    frustration: "medium",
    techLevel: "medium",
  },
  {
    id: "eu-compliance-lead",
    name: "EU Compliance Lead",
    category: "pro",
    group: "region",
    initials: "RC",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("eu-compliance-lead.png"),
    description:
      "Operations lead in Europe who prioritizes trust, privacy, and traceability at every step.",
    traits: ["Demands legal clarity", "Spots trust risks", "Seeks consistency", "Values explicit confirmations"],
    frustration: "medium",
    techLevel: "high",
  },
  {
    id: "ux-researcher",
    category: "pro",
    group: "core",
    name: "UX Researcher",
    initials: "UX",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("ux-researcher.png"),
    description: "Evaluates usability, cognitive load, information flow, and friction at each step.",
    traits: [
      "Nielsen heuristics",
      "Cognitive load",
      "User journey mapping",
      "Spots drop-off points",
      "Suggests concrete alternatives",
    ],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "non-tech",
    name: "Non-technical User",
    category: "simple",
    group: "core",
    initials: "NT",
    avatarBg: "var(--color-error-3)",
    avatarColor: "var(--color-error-1)",
    avatarPhoto: avatar("non-tech.png"),
    description: "Does not understand jargon. If the UI is not obvious, they get lost. Represents the mainstream.",
    traits: ["Needs visual guidance", "Gets frustrated easily", "Skips instructions", "Asks a lot of questions"],
    frustration: "high",
    techLevel: "low",
  },
  {
    id: "power-user",
    name: "Power User",
    category: "simple",
    group: "core",
    initials: "PU",
    avatarBg: "var(--color-accent-200)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("power-user.png"),
    description: "Uses the product to the max. Finds edge cases, wants shortcuts and customization.",
    traits: ["Explores everything", "Looks for shortcuts", "Reports detailed bugs", "Wants APIs/integrations"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "fintech-analyst",
    name: "Fintech Analyst",
    category: "pro",
    group: "industry",
    initials: "AF",
    avatarBg: "var(--color-warning-2)",
    avatarColor: "var(--color-warning-1)",
    avatarPhoto: avatar("fintech-analyst.png"),
    description:
      "Financial product professional evaluating precision, perceived risk, and decision transparency.",
    traits: ["Reads critical microcopy", "Values clear simulations", "Questions defaults", "Looks for advanced controls"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "switcher",
    name: "Dissatisfied Switcher",
    category: "simple",
    group: "core",
    initials: "SI",
    avatarBg: "var(--color-beige-50)",
    avatarColor: "var(--color-basics-black)",
    avatarPhoto: avatar("switcher.png"),
    description: "Coming from a competitor and looking for something better. Compares every detail with what they already know.",
    traits: ["Compares with competitors", "High expectations", "Wants easy migration", "Sensitive to regressions"],
    frustration: "medium",
    techLevel: "high",
  },
  {
    id: "budget-owner",
    name: "Budget Owner",
    category: "simple",
    group: "core",
    initials: "DC",
    avatarBg: "var(--color-error-2)",
    avatarColor: "var(--color-error-1)",
    avatarPhoto: avatar("budget-owner.png"),
    description:
      "Approves the budget. Does not use the product directly but must understand the value.",
    traits: ["Cost-benefit focus", "Transparent pricing", "Must justify purchase", "Little time"],
    frustration: "high",
    techLevel: "low",
  },
  {
    id: "mobile-first",
    name: "Mobile-first User",
    category: "simple",
    group: "core",
    initials: "MF",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("mobile-first.png"),
    description: "Does everything on mobile. If the experience is not responsive, they leave.",
    traits: ["Mobile only", "Performance-sensitive", "Touch gestures", "No horizontal scroll"],
    frustration: "high",
    techLevel: "medium",
  },
  {
    id: "a11y-auditor",
    name: "Accessibility Auditor",
    category: "pro",
    group: "accessibility",
    initials: "AA",
    avatarBg: "var(--color-accent-200)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("a11y-auditor.png"),
    description:
      "Specialist reviewing accessibility end to end with WCAG criteria and an inclusive lens.",
    traits: ["Evaluates contrast and focus", "Checks navigation order", "Looks after labels and states", "Suggests actionable fixes"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "latam-founder",
    name: "LATAM Founder",
    category: "simple",
    group: "region",
    initials: "FL",
    avatarBg: "var(--color-accent-100)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("latam-founder.png"),
    description:
      "Founder in Mexico/Colombia focused on fast growth without sacrificing operational simplicity.",
    traits: ["Watches costs closely", "Decides quickly", "Values Spanish support", "Needs clear flows"],
    frustration: "medium",
    techLevel: "medium",
  },
  {
    id: "edtech-student",
    name: "EdTech Student",
    category: "simple",
    group: "industry",
    initials: "EE",
    avatarBg: "var(--color-beige-50)",
    avatarColor: "var(--color-basics-black)",
    avatarPhoto: avatar("edtech-student.png"),
    description:
      "Multitasking university student who needs to grasp value quickly and move forward with low friction.",
    traits: ["Low on time", "Prefers visual examples", "Gets lost with jargon", "Low tolerance for long onboarding"],
    frustration: "high",
    techLevel: "medium",
  },
  {
    id: "low-vision-advocate",
    name: "Low-vision User",
    category: "simple",
    group: "accessibility",
    initials: "BV",
    avatarBg: "var(--color-error-3)",
    avatarColor: "var(--color-error-1)",
    avatarPhoto: avatar("low-vision-advocate.png"),
    description:
      "Person who relies on high contrast, strong hierarchy, and legible text to complete tasks.",
    traits: ["Sensitive to contrast", "Needs clear typography", "Avoids dense interfaces", "Values visible feedback"],
    frustration: "high",
    techLevel: "medium",
  },
];

export const SOURCE_TYPES: SourceOption[] = [
  { id: "url", label: "URL", icon: "🌐", placeholder: "https://your-app.com/onboarding-flow" },
  { id: "figma", label: "Figma", icon: "🎨", placeholder: "Describe the flow screens in Figma…" },
  { id: "repo", label: "Repo", icon: "📦", placeholder: "Describe routes and component structure…" },
  { id: "description", label: "Manual", icon: "📝", placeholder: "Describe the flow step by step…" },
];
