import type { Persona, SourceOption } from "@/types";

/** Avatares line-art del diseño (`public/assets/design/avatars/`). */
const avatar = (file: string) => `/assets/design/avatars/${file}`;

export const PRESET_PERSONAS: Persona[] = [
  {
    id: "early-adopter",
    name: "Early Adopter Tech",
    category: "simple",
    group: "core",
    initials: "EA",
    avatarBg: "var(--color-accent-100)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("early-adopter.png"),
    description:
      "Usuario técnico, tolera bugs, busca innovación. Evalúa si el concepto es potente aunque la ejecución sea rough.",
    traits: ["Tolerante con los bugs", "Busca innovación", "Da feedback técnico", "Compara con alternativas"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "ui-designer",
    category: "pro",
    group: "core",
    name: "UI Designer",
    initials: "UI",
    avatarBg: "var(--color-accent-100)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("ui-designer.png"),
    description:
      "Evalúa jerarquía visual, consistencia de componentes, espaciado, tipografía, contraste y accesibilidad WCAG.",
    traits: ["Jerarquía visual", "Consistencia DS", "Accesibilidad WCAG", "Espaciado y ritmo", "Contraste y legibilidad"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "product-strategist",
    category: "pro",
    group: "core",
    name: "Product Strategist",
    initials: "PS",
    avatarBg: "var(--color-warning-2)",
    avatarColor: "var(--color-warning-1)",
    avatarPhoto: avatar("product-strategist.png"),
    description: "Evalúa propuesta de valor, activación, retención y monetización.",
    traits: ["Propuesta de valor", "Activación y aha moment", "Retención y churn", "Pricing clarity", "Métricas de impacto"],
    frustration: "medium",
    techLevel: "high",
  },
  {
    id: "busy-manager",
    name: "Manager Ocupado",
    category: "simple",
    group: "core",
    initials: "MO",
    avatarBg: "var(--color-warning-2)",
    avatarColor: "var(--color-warning-1)",
    avatarPhoto: avatar("busy-manager.png"),
    description: "Poco tiempo, necesita entender el valor en 10 segundos. Si no lo ve claro, abandona.",
    traits: ["Impaciente", "Orientado a resultados", "Delega tareas", "Busca ROI claro"],
    frustration: "high",
    techLevel: "medium",
  },
  {
    id: "skeptic",
    name: "Escéptico Pragmático",
    category: "simple",
    group: "core",
    initials: "EP",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("skeptic-v2.png"),
    description: "Ha visto muchas herramientas fallar. Necesita pruebas concretas y casos de uso reales.",
    traits: ["Desconfiado", "Pide evidencia", "Compara precios", "Busca casos de éxito"],
    frustration: "medium",
    techLevel: "medium",
  },
  {
    id: "eu-compliance-lead",
    name: "Responsable Compliance UE",
    category: "pro",
    group: "region",
    initials: "RC",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("eu-compliance-lead.png"),
    description: "Lider de operaciones en Europa que prioriza confianza, privacidad y trazabilidad en cada paso.",
    traits: ["Exige claridad legal", "Detecta riesgos de confianza", "Busca consistencia", "Valora confirmaciones explicitas"],
    frustration: "medium",
    techLevel: "high",
  },
  {
    id: "ux-researcher",
    category: "pro",
    group: "core",
    name: "UX Researcher",
    initials: "UX",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("ux-researcher.png"),
    description:
      "Evalúa usabilidad, carga cognitiva, flujo de información y fricción en cada paso.",
    traits: [
      "Heurísticas de Nielsen",
      "Carga cognitiva",
      "User journey mapping",
      "Detecta puntos de abandono",
      "Propone alternativas concretas",
    ],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "non-tech",
    name: "Usuario No Técnico",
    category: "simple",
    group: "core",
    initials: "NT",
    avatarBg: "var(--color-error-3)",
    avatarColor: "var(--color-error-1)",
    avatarPhoto: avatar("non-tech.png"),
    description: "No entiende jerga técnica. Si la UI no es obvia, se pierde. Representa al mainstream.",
    traits: ["Necesita guía visual", "Se frustra fácil", "No lee instrucciones", "Pregunta mucho"],
    frustration: "high",
    techLevel: "low",
  },
  {
    id: "power-user",
    name: "Power User",
    category: "simple",
    group: "core",
    initials: "PU",
    avatarBg: "var(--color-accent-200)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("power-user.png"),
    description: "Usa el producto al máximo. Encuentra edge casos, quiere atajos y personalización.",
    traits: ["Explora todo", "Busca atajos", "Reporta bugs detallados", "Quiere API/integraciones"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "fintech-analyst",
    name: "Analista Fintech",
    category: "pro",
    group: "industry",
    initials: "AF",
    avatarBg: "var(--color-warning-2)",
    avatarColor: "var(--color-warning-1)",
    avatarPhoto: avatar("fintech-analyst.png"),
    description: "Profesional de producto financiero que evalua precision, riesgo percibido y transparencia de decisiones.",
    traits: ["Lee microcopy critico", "Valora simulaciones claras", "Cuestiona defaults", "Busca controles avanzados"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "switcher",
    name: "Switcher Insatisfecho",
    category: "simple",
    group: "core",
    initials: "SI",
    avatarBg: "var(--color-beige-50)",
    avatarColor: "var(--color-basics-black)",
    avatarPhoto: avatar("switcher.png"),
    description: "Viene de usar un competidor y busca algo mejor. Compara cada detalle con lo que ya conoce.",
    traits: ["Compara con competencia", "Expectativas altas", "Busca migración fácil", "Sensible a regresiones"],
    frustration: "medium",
    techLevel: "high",
  },
  {
    id: "budget-owner",
    name: "Decisor de Compra",
    category: "simple",
    group: "core",
    initials: "DC",
    avatarBg: "var(--color-error-2)",
    avatarColor: "var(--color-error-1)",
    avatarPhoto: avatar("budget-owner.png"),
    description:
      "Es quien aprueba el presupuesto. No usa el producto directamente pero necesita entender el valor.",
    traits: ["Evalúa coste-beneficio", "Pricing transparente", "Necesita justificar compra", "Poco tiempo"],
    frustration: "high",
    techLevel: "low",
  },
  {
    id: "mobile-first",
    name: "Mobile-First User",
    category: "simple",
    group: "core",
    initials: "MF",
    avatarBg: "var(--color-info-2)",
    avatarColor: "var(--color-info-1)",
    avatarPhoto: avatar("mobile-first.png"),
    description: "Hace todo desde el móvil. Si la experiencia no es responsive, abandona.",
    traits: ["Solo usa móvil", "Sensible a rendimiento", "Gestos táctiles", "No tolera scroll horizontal"],
    frustration: "high",
    techLevel: "medium",
  },
  {
    id: "a11y-auditor",
    name: "Auditora de Accesibilidad",
    category: "pro",
    group: "accessibility",
    initials: "AA",
    avatarBg: "var(--color-accent-200)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("a11y-auditor.png"),
    description: "Especialista que revisa accesibilidad de punta a punta con criterio WCAG y enfoque inclusivo.",
    traits: ["Evalua contraste y foco", "Revisa orden de navegacion", "Cuida labels y estados", "Propone mejoras accionables"],
    frustration: "low",
    techLevel: "high",
  },
  {
    id: "latam-founder",
    name: "Fundadora LATAM",
    category: "simple",
    group: "region",
    initials: "FL",
    avatarBg: "var(--color-accent-100)",
    avatarColor: "var(--color-accent-700)",
    avatarPhoto: avatar("latam-founder.png"),
    description: "Emprendedora de Mexico/Colombia con foco en crecer rapido sin perder simplicidad operativa.",
    traits: ["Mira costos al detalle", "Decide rapido", "Valora soporte en espanol", "Necesita flujos claros"],
    frustration: "medium",
    techLevel: "medium",
  },
  {
    id: "edtech-student",
    name: "Estudiante EdTech",
    category: "simple",
    group: "industry",
    initials: "EE",
    avatarBg: "var(--color-beige-50)",
    avatarColor: "var(--color-basics-black)",
    avatarPhoto: avatar("edtech-student.png"),
    description: "Universitario multitarea que necesita entender rapido el valor y avanzar sin friccion.",
    traits: ["Poco tiempo", "Prefiere ejemplos visuales", "Se pierde con jerga", "Tolera poco onboarding largo"],
    frustration: "high",
    techLevel: "medium",
  },
  {
    id: "low-vision-advocate",
    name: "Usuario con Baja Vision",
    category: "simple",
    group: "accessibility",
    initials: "BV",
    avatarBg: "var(--color-error-3)",
    avatarColor: "var(--color-error-1)",
    avatarPhoto: avatar("low-vision-advocate.png"),
    description: "Persona que depende de alto contraste, jerarquia fuerte y textos legibles para completar tareas.",
    traits: ["Sensibilidad a contraste", "Necesita tipografia clara", "Evita interfaces densas", "Valora feedback visible"],
    frustration: "high",
    techLevel: "medium",
  },
];

export const SOURCE_TYPES: SourceOption[] = [
  { id: "url", label: "URL", icon: "🌐", placeholder: "https://tu-app.com/flujo-onboarding" },
  { id: "figma", label: "Figma", icon: "🎨", placeholder: "Describe las pantallas del flujo en Figma..." },
  { id: "repo", label: "Repo", icon: "📦", placeholder: "Describe la estructura de rutas y componentes..." },
  { id: "description", label: "Manual", icon: "📝", placeholder: "Describe el flujo paso a paso..." },
];
